### ISSUE TITLE
Is there a way to deactivate the plugin again?

### ISSUE THREAD

**Issue by cm-cm-cm-cm** [Nikita-schetko/capacitor-suppress-longpress#1]
I'd like to supress longpress gesture only in some routes. Is there a possibility to disable it again?

**Comment by Nikita-schetko** [comment]
Hi ! Thank you for your question; 
Now, it's not possible, but i'm going to add this small feature in few days;

**Comment by cm-cm-cm-cm** [comment]
Oh that's cool, thank you!

I kind of got it to work myself with an additional function, maybe you can use this for your solution:

    @objc func deactivateService(_ call: CAPPluginCall) {
        print("activateService!")
        let webView = self.bridge?.webView

        // add this in main thread
        DispatchQueue.main.async {
            for recognizer in webView?.gestureRecognizers ?? [] {
                webView?.removeGestureRecognizer(recognizer)
            }
            // resolve plugin call
            call.resolve()
        }
    }

**Comment by Nikita-schetko** [comment]
Implemented ! Hope now it will fit you need! :)
