### ISSUE TITLE
Update plugin for Capacitor 4

### ISSUE THREAD

**Issue by mariusbolik** [Nikita-schetko/capacitor-suppress-longpress#4]
Hello,

I can't compile my app using Capacitor 4.3. This is the error I get:
<img width="602" alt="Bildschirmfoto 2022-09-30 um 16 51 02" src="https://user-images.githubusercontent.com/39862171/193297114-59ea4462-8ece-43c3-810d-a715a2d39e81.png">

Regards,
Marius

**Comment by mariusbolik** [comment]
I created a pull request for that: https://github.com/Nikita-schetko/capacitor-suppress-longpress-gesture/pull/6

**Comment by Nikita-schetko** [comment]
Thank you, Marius ! Just have merged it !
