### ISSUE TITLE
feature request: v5

### ISSUE THREAD

**Issue by AndreyYolkin** [Nikita-schetko/capacitor-suppress-longpress#7]
Hello, I've found your plugin and it seems to be the solution I need. But I've already migrated application to capacitor v5. However, Ionic also released a guide: https://capacitorjs.com/docs/updating/plugins/5-0 with some easy steps. Could you apply proposed changes and release new version?

**Comment by mariusbolik** [comment]
I opened a PR: https://github.com/Nikita-schetko/capacitor-suppress-longpress-gesture/pull/8

**Comment by Nikita-schetko** [comment]
Thanks guys! Done, merged, now it supports capacitor v5
