### ISSUE TITLE
Update to Capacitor 6

### ISSUE THREAD

**Issue by cm-cm-cm-cm** [Nikita-schetko/capacitor-suppress-longpress#9]
Hello, I've found your plugin and it seems to be the solution I need. But I've already migrated application to capacitor v6. However, Ionic also released a guide: https://capacitorjs.com/docs/updating/plugins/5-0 with some easy steps. Could you apply proposed changes and release new version?

**Comment by cm-cm-cm-cm** [comment]
PR: https://github.com/Nikita-schetko/capacitor-suppress-longpress-gesture/pull/10

**Comment by Nikita-schetko** [comment]
Hello ! Thanks for updating package, merged into master and published in npm :)
